from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class PinglyRepository(Protocol):
    async def get_user_by_tg_id(self, tg_id: int) -> dict[str, Any] | None: ...
    async def get_user_by_id(self, user_id: str) -> dict[str, Any] | None: ...
    async def upsert_user(self, role: str, tg_id: int, full_name: str, tg_username: str | None) -> dict[str, Any]: ...
    async def update_user_profile(self, user_id: str, full_name: str | None = None, role: str | None = None) -> dict[str, Any] | None: ...
    async def upsert_tutor_user(self, tg_id: int, full_name: str, tg_username: str | None) -> dict[str, Any]: ...
    async def set_user_telegram(self, user_id: str, tg_id: int, tg_username: str | None) -> dict[str, Any] | None: ...
    async def get_user_by_email(self, email: str) -> dict[str, Any] | None: ...
    async def create_email_tutor(self, email: str, password_hash: str, full_name: str, email_verified: bool = True) -> dict[str, Any]: ...
    async def set_verification_code(self, user_id: str, code: str, expires_at: str) -> None: ...
    async def mark_email_verified(self, user_id: str) -> dict[str, Any] | None: ...
    async def create_invited_student(self, tutor_user_id: str, name: str, tg_username: str, invite_token: str) -> dict[str, Any]: ...
    async def get_student_by_invite_token(self, invite_token: str) -> dict[str, Any] | None: ...
    async def link_student_to_tg(self, invite_token: str, tg_id: int, full_name: str, tg_username: str | None) -> dict[str, Any]: ...
    async def list_tutor_students(self, tutor_user_id: str, search: str | None = None) -> list[dict[str, Any]]: ...
    async def get_student_for_tutor(self, tutor_user_id: str, student_id: str) -> dict[str, Any] | None: ...
    async def get_student_for_user(self, student_user_id: str) -> dict[str, Any] | None: ...
    async def update_student_profile(self, student_id: str, patch: dict[str, Any]) -> dict[str, Any] | None: ...
    async def set_student_package(self, student_id: str, size: int | None, started_at: str | None) -> dict[str, Any] | None: ...
    async def list_active_package_students(self) -> list[dict[str, Any]]: ...
    async def get_tutor_student_relation(self, tutor_user_id: str, student_id: str) -> dict[str, Any] | None: ...
    async def delete_tutor_student(self, tutor_user_id: str, student_id: str) -> None: ...
    async def set_tutor_student_note(self, tutor_user_id: str, student_id: str, note: str | None) -> None: ...
    async def create_schedule_rule(self, tutor_user_id: str, student_id: str, day_of_week: int, lesson_time: str, duration_minutes: int, recurrence: str = "weekly", interval_n: int = 1, weekdays: list[int] | None = None, start_date: str | None = None) -> dict[str, Any]: ...
    async def get_schedule_rule(self, tutor_user_id: str, rule_id: str) -> dict[str, Any] | None: ...
    async def list_schedule_rules(self, tutor_user_id: str) -> list[dict[str, Any]]: ...
    async def update_schedule_rule(self, rule_id: str, patch: dict[str, Any], tutor_user_id: str | None = None) -> dict[str, Any] | None: ...
    async def list_future_lessons_for_rule(self, rule_id: str, after: datetime, tutor_user_id: str | None = None) -> list[dict[str, Any]]: ...
    async def create_lesson(self, tutor_user_id: str, student_id: str, starts_at: datetime, subject_id: str | None = None, schedule_rule_id: str | None = None, public_comment: str | None = None) -> dict[str, Any]: ...
    async def list_lessons_for_tutor(self, tutor_user_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    async def list_lessons_for_student_user(self, student_user_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    async def get_next_lesson_for_student_user(self, student_user_id: str) -> dict[str, Any] | None: ...
    async def get_lesson_for_tutor(self, tutor_user_id: str, lesson_id: str) -> dict[str, Any] | None: ...
    async def update_lesson_status(self, tutor_user_id: str, lesson_id: str, status: str, starts_at: datetime | None = None) -> dict[str, Any] | None: ...
    async def update_lesson_fields(self, lesson_id: str, patch: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_lesson(self, tutor_user_id: str, lesson_id: str) -> None: ...
    async def set_lesson_payment(self, tutor_user_id: str, lesson_id: str, paid: bool) -> dict[str, Any] | None: ...
    async def get_lesson_by_id(self, lesson_id: str) -> dict[str, Any] | None: ...
    async def create_subscription_payment(self, user_id: str, transaction_id: str, amount_rub: int) -> dict[str, Any]: ...
    async def upsert_subscription_payment_pending(self, user_id: str, transaction_id: str, amount_rub: int) -> dict[str, Any] | None: ...
    async def confirm_subscription_payment_once(self, transaction_id: str) -> dict[str, Any] | None: ...
    async def get_subscription_payment_by_transaction(self, transaction_id: str) -> dict[str, Any] | None: ...
    async def get_latest_pending_payment_for_user(self, user_id: str) -> dict[str, Any] | None: ...
    async def mark_subscription_payment(self, transaction_id: str, status: str, confirmed: bool = False) -> dict[str, Any] | None: ...
    async def activate_subscription(self, user_id: str, days: int = 30) -> dict[str, Any] | None: ...
    async def create_homework(self, tutor_user_id: str, student_id: str, title: str, description: str | None, due_at: datetime | None) -> dict[str, Any]: ...
    async def list_homework_for_tutor(self, tutor_user_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    async def list_homework_for_student_user(self, student_user_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    async def update_homework_status(self, user_id: str, homework_id: str, status: str, tutor_comment: str | None = None) -> dict[str, Any] | None: ...
    async def create_notification(self, user_id: str, ntype: str, title: str, body: str, payload: dict[str, Any] | None = None, scheduled_for: datetime | None = None) -> dict[str, Any]: ...
    async def list_notifications_for_user(self, user_id: str, limit: int = 50) -> list[dict[str, Any]]: ...
    async def list_due_notifications(self, now: datetime, limit: int = 100) -> list[dict[str, Any]]: ...
    async def mark_notification_sent(self, notification_id: str) -> None: ...
    async def analytics_for_tutor(self, tutor_user_id: str) -> dict[str, Any]: ...
    async def create_web_token(self, user_id: str, token_hash: str, expires_at: datetime) -> None: ...
    async def consume_web_token(self, token_hash: str, now: datetime) -> dict[str, Any] | None: ...
    async def get_tutor_profile(self, tutor_user_id: str) -> dict[str, Any] | None: ...
    async def get_tutor_profile_by_slug(self, slug: str) -> dict[str, Any] | None: ...
    async def update_tutor_profile(self, tutor_user_id: str, patch: dict[str, Any]) -> dict[str, Any] | None: ...
    async def create_booking_request(self, tutor_user_id: str, name: str, contact: str, preferred_time: str | None, comment: str | None) -> dict[str, Any]: ...
    async def list_booking_requests(self, tutor_user_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    async def update_booking_request_status(self, tutor_user_id: str, request_id: str, status: str) -> dict[str, Any] | None: ...
    async def create_homework_template(self, tutor_user_id: str, title: str, description: str | None) -> dict[str, Any]: ...
    async def list_homework_templates(self, tutor_user_id: str, limit: int = 100) -> list[dict[str, Any]]: ...
    async def delete_homework_template(self, tutor_user_id: str, template_id: str) -> None: ...
    async def list_tutors_with_trial(self) -> list[dict[str, Any]]: ...
    async def get_user_by_referral_code(self, code: str) -> dict[str, Any] | None: ...
    async def set_referred_by(self, user_id: str, referrer_id: str) -> None: ...
    async def extend_trial(self, user_id: str, days: int) -> None: ...
    async def grant_referral_reward(self, user_id: str) -> bool: ...
