-- OUTDATED — do not run. This file described a pre-migration schema
-- (bare `tutors`/`students`/`lessons`/`reminders` tables) that no longer
-- matches the application code, which reads/writes `users`, `student_profiles`,
-- `schedule_rules`, `lessons`, `notifications`, `subscription_payments`, etc.
--
-- The real, current schema is the union of migrations/001..019_*.sql, applied
-- in order (via Supabase MCP or the SQL Editor). Bootstrapping a new project?
-- Run every file in migrations/ in numeric order — there is no single
-- consolidated schema.sql.
